sudo: required
services:
  - docker

before_install:
  - docker build -t ppanan/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ppanan/client-test npm test -- --coverage

after_success:
  - docker build -t ppanan/multi-client ./client
  - docker build -t ppanan/multi-nginx ./nginx
  - docker build -t ppanan/multi-server ./server
  - docker build -t ppanan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ppanan/multi-client
  - docker push ppanan/multi-nginx
  - docker push ppanan/multi-server
  - docker push ppanan/multi-worker